version: 2
build:
  os: ubuntu-24.04
  apt_packages:
    - libigraph-dev
    - libeigen3-dev
  tools:
    python: "mambaforge-23.11"
  jobs:
    install:
      - pip install . --no-deps
conda:
  environment: doc/readthedocs-env.yaml
sphinx:
  configuration: doc/source/conf.py
  fail_on_warning: false
