version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-23.11"
conda:
  environment: doc/readthedocs-env.yaml
python:
   install:
     - method: pip
       path: .
sphinx:
   configuration: doc/source/conf.py
