version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-23.11"
conda:
  environment: doc/readthedocs-env.yaml
python:
   commands:
     - pip install . --no-deps
sphinx:
   configuration: doc/source/conf.py
