[build-system]
requires = ["setuptools",
            "wheel",
            "numpy>=2.0.0rc1",
            "cython>=3.0.2",
            "igraph",
            "eigen",
]

[project]
name = "StructuralGT"
version = "0.0.1"
dependencies = [
        'numpy>=1.18.5',
        'scipy',
        'scikit-image',
        'matplotlib',
        'networkx',
        'opencv-python',
        'pandas',
        'Pillow<10.1.0,>=8.3.2',
        'Cython',
        'gsd',
        'python-igraph',
        'eigen',
        'pytest',
        'cmake',
        'freud',
]
