"""Protocol for the app controller."""

from typing import Any, Protocol, runtime_checkable

import numpy as np
from PySide6.QtCore import SignalInstance


@runtime_checkable
class AppFacade(Protocol):
    """Protocol for the app controller used by the UI layer."""

    # Signals
    change_view_signal: SignalInstance
    alert_signal: SignalInstance
    handler_changed_signal: SignalInstance
    binarize_finished_signal: SignalInstance
    extract_graph_finished_signal: SignalInstance
    compute_graph_properties_finished_signal: SignalInstance
    task_changed_signal: SignalInstance

    # Main thread methods
    def add_network(self, folder_path: str, dim: int) -> None: ...
    def add_point_network(self, file_path: str) -> None: ...
    def delete_network(self, index: int) -> None: ...

    def get_selected_handler(self) -> Any: ...
    def set_selected_index(self, index: int) -> None: ...
    def set_selected_slice_index(self, index: int) -> None: ...

    def get_selected_slice_raw_image(self, index: int) -> np.ndarray | None: ...
    def get_selected_slice_binarized_image(
        self, index: int
    ) -> np.ndarray | None: ...
    def get_selected_extracted_graph(self) -> str | None: ...

    def plot_selected_handler(self, plot_name: str, ax: Any) -> None: ...

    # Worker thread methods
    def binarize_selected_network(self, options: dict) -> None: ...
    def extract_graph_from_selected_network(self, weight_type: Any = None) -> None: ...
    def compute_graph_properties_from_selected_network(
        self, options: dict
    ) -> None: ...
    def cancel_task(self, task_id: str) -> None: ...
    def cleanup_threads(self) -> None: ...
