name: Python Package using Conda

on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: ["3.12","3.13"]
        python: ['312','313']

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.2.2

    - name: Create Testing Environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: .github/workflows/conda-envs/py${{ matrix.python }}-conda-lock.yml
        channels: conda-forge,defaults
        activate-environment: test
        auto-update-conda: false
        auto-activate-base: false
        show-channel-urls: true
        miniforge-version: latest

    - name: Install package
      shell: bash -l {0}  # conda stetup requires this special shell
      run: |
        pip install . --no-deps
    - name: Run tests
      shell: bash -l {0}  # conda setup requires this special shell
      run: |
        pytest
